version: '3.7'
services:
  docker-sample:
    container_name: "docker-sample"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes: 
      - ./php:/var/www
    extra_hosts:
      - "plat.local:127.0.0.1"
    hostname: plat.local
    domainname: local 
    ports:
      - 80:80
